### Python Version Check

In [5]:
import sys
#check python version
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
  print("Hello, world")
  print(f"Python version: {sys.version}")
else:
  print("Please use Python 3.6 or higher")

Hello, world
Python version: 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]


### Data types in python

In [9]:
#Mutable Data type Example (list)
my_list = [1, 2, 3]
# Modifying the list (changing contents)
my_list.append(4)
print("Modified List:", my_list)
# Immutable Data Type Example (Tuple)
my_tuple = (1, 2, 3)
print("Original Tuple:", my_tuple)

Modified List: [1, 2, 3, 4]
Original Tuple: (1, 2, 3)


In [11]:
# Trying to modify the tuple (will raise an error)
# my_tuple.append(4) # Uncommenting this line will raise an AttributeError

### Some Common Data Types in Python:

### Numeric

In [24]:
age = 23 #int
pi = 3.14 #float
temperature = -5.5 #float
print("data type of variable age = ", type(age))
print("data type of variable pi = ", type(pi))
print("data type of variable temperature = ", type(temperature))

data type of variable age =  <class 'int'>
data type of variable pi =  <class 'float'>
data type of variable temperature =  <class 'float'>


### str:

In [34]:
name = "Alice"
greeting = 'Hello'
address = "123 Main St"
print("data type of the variable name = ",type(name))
print("data type of the variable greeting = ",type(greeting))
print("data type of the variable address = ",type(address))
# slice only one element
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])
# slice a range of elements
print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])

data type of the variable name =  <class 'str'>
data type of the variable greeting =  <class 'str'>
data type of the variable address =  <class 'str'>
The first letter of the name is: A
The last letter of the name is: e
The second letter to the fourth of the name is: lic
The first two letters of the name are: Al
Substring starting from the third letter is: ice


### list

In [41]:
list1 = [1, 2, 3, 4]
mixed_list = [12, "Hello", True]
# List is mutable
mixed_list[0] = False
mixed_list

[False, 'Hello', True]

### tuple:

In [50]:
colors = ('red', 'green', 'yellow', 'blue')
print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])
colors[0] = 'purple'
colors # will generate an error as tuple is immutable.

First element: red
Last two elements: ('yellow', 'blue')
Middle two elements: ('green', 'yellow')


TypeError: 'tuple' object does not support item assignment

### Mapping:

In [57]:
person = {'name': 'John', 'age': 30, 'city': 'Pittsburgh'}
print(f"Hello my name is {person['name']}. I am {person['age']} years old and I live at {person['city']}")
print("All keys", list(person.keys()))
print("All values", list(person.values()))

Hello my name is John. I am 30 years old and I live at Pittsburgh
All keys ['name', 'age', 'city']
All values ['John', 30, 'Pittsburgh']


### Set:

In [60]:
unique_numbers = {1,2,3,3,3,3,4,5}
print(unique_numbers)

{1, 2, 3, 4, 5}


### Boolean:

In [65]:
is_student = True
has_license = False
print("data type of the variable is_student = ",type(is_student))
print("data type of the variable has_license = ",type(has_license))

data type of the variable is_student =  <class 'bool'>
data type of the variable has_license =  <class 'bool'>


### Special

In [70]:
result = None

### Logical Statements:

In [75]:
num = 10
if num > 0:
    print("Positive")
elif num == 0:
    print("Zero")
else:
    print("Non-positive")

Positive


In [79]:
x = 5
y = 10
if x > 0 and y < 20:
    print("Both conditions are true")
if x > 0 or y > 20:
    print("At least one condition is true")
if not x == 0:
    print("x is not equal to 0")

Both conditions are true
At least one condition is true
x is not equal to 0


In [81]:
# Define two boolean variables
a = True
b = False
# Using the ’and’ operator
if a and b:
    print("Both a and b are True")
else:
    print("Either a or b is False") # This will be printed
# Using the ’or’ operator
if a or b:
    print("At least one of a or b is True") # This will be printed
else:
    print("Both a and b are False")
# Using the ’not’ operator
if not a:
    print("a is False") # This will not be printed
else:
    print("a is True") # This will be printed

Either a or b is False
At least one of a or b is True
a is True


In [2]:
# for loop:
fruits = ["apple", "banana","cherry"]
for fruit in fruits:
    print(fruit)
# While loop:
count = 0
while count < 5:
    print("Count is:", count)
    count += 1
# Break
fruits = ["apple", "banana", "orange"]
print("loop 1")
for fruit in fruits:
    print(fruit)
    if fruit == "apple":
        break
# Continiue
print("loop 2")
for fruit in fruits:
    if fruit == "apple":
        continue
    else:
        print(fruit)

apple
banana
cherry
Count is: 0
Count is: 1
Count is: 2
Count is: 3
Count is: 4
loop 1
apple
loop 2
banana
orange


In [8]:
def add_binary(a, b):
    '''
    Returns the sum of two decimal numbers in binary digits.
    Parameters:
    a (int): A decimal integer
    b (int): Another decimal integer
    Returns:
    binary_sum (str): Binary string of the sum of a and b
    '''
    binary_sum = bin(a+b)[2:]
    return binary_sum


### Built - in - Functions:

In [10]:
print("Hello, World!") # Output: Hello, World!
length = len("Hello") # Output: 5
data_type = type(42) # Output: <class ’int’>
total = sum([1, 2, 3]) # Output: 6

Hello, World!


### Built - in - Methods:

In [12]:
# str.upper(): Converts all characters in a string to uppercase.
message = "hello".upper() # Output: "HELLO"
# list.append(): Adds an element to the end of a list.
fruits = ["apple", "banana"]
fruits.append("cherry") # Output: ["apple", "banana", "cherry"]
# dict.get(): Returns the value associated with a key in a dictionary.
info = {"name": "Alice", "age": 25}
age = info.get("age") # Output: 25

### User - Defined - Function:

In [16]:
def temperature_converter():
    """
    Converts temperature between Celsius and Fahrenheit.
    This function prompts the user to specify the conversion type (Celsius to Fahrenheit or
    Fahrenheit to Celsius)
    and then asks for the temperature value. It calculates and returns the converted temperature.
    Returns:
    float: The converted temperature value.
    """
    print("Choose conversion type:")
    print("1. Celsius to Fahrenheit")
    print("2. Fahrenheit to Celsius")
    # Get conversion choice from user
    choice = input("Enter 1 or 2: ")
    if choice == "1":
        # Celsius to Fahrenheit conversion
        celsius = float(input("Enter temperature in Celsius: "))
        fahrenheit = (celsius * 9/5) + 32
        print(f"{celsius}C is equal to {fahrenheit}F")
        return fahrenheit
    elif choice == "2":
        # Fahrenheit to Celsius conversion
        fahrenheit = float(input("Enter temperature in Fahrenheit: "))
        celsius = (fahrenheit - 32) * 5/9
        print(f"{fahrenheit}F is equal to {celsius}C")
        return celsius
    else:
        print("Invalid choice. Please enter 1 or 2.")
        return None
# Call the function
temperature_converter()

Choose conversion type:
1. Celsius to Fahrenheit
2. Fahrenheit to Celsius


Enter 1 or 2:  1
Enter temperature in Celsius:  36


36.0C is equal to 96.8F


96.8

### Global variables:

In [21]:
x = 10 # Global Variable.
def print_global():
    print(x) # Accessing global variable
print_global() # Output: 10

10


### Local Variables:

In [26]:
def print_local():
    y = 5 # Local variable
    print(y)
print_local() # Output: 5
print(y) # This would cause an error because y is not accessible outside the function

5


NameError: name 'y' is not defined

### Accessing and Modifying Global Variables Inside a Function

In [29]:
x = 10 # Global variable
def modify_global():
    global x # Declaring x as global
    x = 20 # Modifying global x
modify_global()
print(x) # Output: 20

20


In [33]:
try:
    num = int(input("Enter a number: "))
    print("Result:", 10 / num)
except ZeroDivisionError:
    print("Cannot divide by zero.")
except ValueError:
    print("Invalid input. Please enter a number.")

Enter a number:  12


Result: 0.8333333333333334


In [35]:
try:
    file = open("example.txt", "r")
    data = file.read()
except FileNotFoundError:
    print("File not found.")
finally:
    file.close() # Ensures the file is closed

File not found.


NameError: name 'file' is not defined

In [37]:
def check_age(age):
    if age < 0:
        raise ValueError("Age cannot be negative.")
    else:
        print("Valid age")
try:
    check_age(-1)
except ValueError as e:
    print(e)

Age cannot be negative.


### 4.1 Exercise on Functions:
### Task - 1:

In [42]:
def convert_length(value, from_unit):
    """
    Converts length between meters and feet.
    :param value: The numerical value to convert.
    :param from_unit: The unit of the input value ('m' or 'ft').
    :return: Converted value in the target unit.
    """
    if from_unit == 'm':
        return value * 3.28084  # Meters to feet
    elif from_unit == 'ft':
        return value / 3.28084  # Feet to meters
    else:
        raise ValueError("Invalid length unit")

def convert_weight(value, from_unit):
    """
    Converts weight between kilograms and pounds.
    :param value: The numerical value to convert.
    :param from_unit: The unit of the input value ('kg' or 'lbs').
    :return: Converted value in the target unit.
    """
    if from_unit == 'kg':
        return value * 2.20462  # Kilograms to pounds
    elif from_unit == 'lbs':
        return value / 2.20462  # Pounds to kilograms
    else:
        raise ValueError("Invalid weight unit")

def convert_volume(value, from_unit):
    """
    Converts volume between liters and gallons.
    :param value: The numerical value to convert.
    :param from_unit: The unit of the input value ('L' or 'gal').
    :return: Converted value in the target unit.
    """
    if from_unit == 'L':
        return value * 0.264172  # Liters to gallons
    elif from_unit == 'gal':
        return value / 0.264172  # Gallons to liters
    else:
        raise ValueError("Invalid volume unit")

def main():
    print("Unit Converter: Length, Weight, Volume")
    print("1. Length (meters <-> feet)")
    print("2. Weight (kilograms <-> pounds)")
    print("3. Volume (liters <-> gallons)")
    
    try:
        choice = int(input("Select conversion type (1-3): "))
        if choice not in [1, 2, 3]:
            raise ValueError("Invalid selection")
        
        value = float(input("Enter value to convert: "))
        
        if choice == 1:
            unit = input("Enter unit (m or ft): ").strip().lower()
            converted = convert_length(value, unit)
            target_unit = 'ft' if unit == 'm' else 'm'
        elif choice == 2:
            unit = input("Enter unit (kg or lbs): ").strip().lower()
            converted = convert_weight(value, unit)
            target_unit = 'lbs' if unit == 'kg' else 'kg'
        elif choice == 3:
            unit = input("Enter unit (L or gal): ").strip().lower()
            converted = convert_volume(value, unit)
            target_unit = 'gal' if unit == 'l' else 'L'
        
        print(f"Converted Value: {converted:.2f} {target_unit}")
    except ValueError as e:
        print(f"Error: {e}")
    except Exception:
        print("An unexpected error occurred.")

if __name__ == "__main__":
    main()

Unit Converter: Length, Weight, Volume
1. Length (meters <-> feet)
2. Weight (kilograms <-> pounds)
3. Volume (liters <-> gallons)


Select conversion type (1-3):  1
Enter value to convert:  1
Enter unit (m or ft):  ft


Converted Value: 0.30 m


In [44]:
def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.
    :param numbers: List of numerical values.
    :return: Sum of the numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.
    :param numbers: List of numerical values.
    :return: Average of the numbers.
    """
    return sum(numbers) / len(numbers) if numbers else 0

def find_maximum(numbers):
    """
    Finds the maximum number in a list.
    :param numbers: List of numerical values.
    :return: Maximum number in the list.
    """
    return max(numbers)

def find_minimum(numbers):
    """
    Finds the minimum number in a list.
    :param numbers: List of numerical values.
    :return: Minimum number in the list.
    """
    return min(numbers)

def main():
    print("Mathematical Operations on a List of Numbers")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")
    
    try:
        choice = int(input("Select an operation (1-4): "))
        if choice not in [1, 2, 3, 4]:
            raise ValueError("Invalid selection")
        
        numbers_input = input("Enter a list of numbers separated by spaces: ").strip()
        numbers = list(map(float, numbers_input.split()))
        if not numbers:
            raise ValueError("The list cannot be empty")
        
        if choice == 1:
            result = calculate_sum(numbers)
        elif choice == 2:
            result = calculate_average(numbers)
        elif choice == 3:
            result = find_maximum(numbers)
        elif choice == 4:
            result = find_minimum(numbers)
        
        print(f"Result: {result}")
    except ValueError as e:
        print(f"Error: {e}")
    except Exception:
        print("An unexpected error occurred.")

if __name__ == "__main__":
    main()

Mathematical Operations on a List of Numbers
1. Sum
2. Average
3. Maximum
4. Minimum


Select an operation (1-4):  1
Enter a list of numbers separated by spaces:  1 2 3


Result: 6.0


Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [47]:
def extract_every_other(lst):
    """
    Extracts every other element from a list, starting from the first element.
    :param lst: The input list.
    :return: A new list containing every other element.
    """
    return lst[::2]

# Example usage
example_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(example_list)
print(result)  # Output: [1, 3, 5]


[1, 3, 5]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [50]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list, starting from the specified index and ending at the specified index (inclusive).
    :param lst: The input list.
    :param start: The starting index.
    :param end: The ending index (inclusive).
    :return: A sublist from start to end.
    """
    return lst[start:end+1]

# Example usage
example_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4
result = get_sublist(example_list, start_index, end_index)
print(result)  # Output: [3, 4, 5]


[3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [53]:
def reverse_list(lst):
    """
    Reverses a list using slicing.
    :param lst: The input list.
    :return: A new list with elements in reverse order.
    """
    return lst[::-1]

# Example usage
example_list = [1, 2, 3, 4, 5]
result = reverse_list(example_list)
print(result)  # Output: [5, 4, 3, 2, 1]

[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [56]:
def remove_first_last(lst):
    """
    Removes the first and last elements from a list and returns the resulting sublist.
    :param lst: The input list.
    :return: A new list without the first and last elements.
    """
    return lst[1:-1] if len(lst) > 2 else []

# Example usage
example_list = [1, 2, 3, 4, 5]
result = remove_first_last(example_list)
print(result)  # Output: [2, 3, 4]


[2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [59]:
def remove_first_last(lst):
    """
    Removes the first and last elements from a list and returns the resulting sublist.
    :param lst: The input list.
    :return: A new list without the first and last elements.
    """
    return lst[1:-1] if len(lst) > 2 else []

def get_first_n(lst, n):
    """
    Extracts the first n elements from a list.
    :param lst: The input list.
    :param n: Number of elements to extract.
    :return: A new list containing the first n elements.
    """
    return lst[:n]

# Example usage
example_list = [1, 2, 3, 4, 5]
result = remove_first_last(example_list)
print(result)  # Output: [2, 3, 4]

n = 3
first_n_result = get_first_n(example_list, n)
print(first_n_result)  # Output: [1, 2, 3]


[2, 3, 4]
[1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [62]:
def remove_first_last(lst):
    """
    Removes the first and last elements from a list and returns the resulting sublist.
    :param lst: The input list.
    :return: A new list without the first and last elements.
    """
    return lst[1:-1] if len(lst) > 2 else []

def get_first_n(lst, n):
    """
    Extracts the first n elements from a list.
    :param lst: The input list.
    :param n: Number of elements to extract.
    :return: A new list containing the first n elements.
    """
    return lst[:n]

def get_last_n(lst, n):
    """
    Extracts the last n elements from a list.
    :param lst: The input list.
    :param n: Number of elements to extract.
    :return: A new list containing the last n elements.
    """
    return lst[-n:]

# Example usage
example_list = [1, 2, 3, 4, 5]
result = remove_first_last(example_list)
print(result)  # Output: [2, 3, 4]

n = 3
first_n_result = get_first_n(example_list, n)
print(first_n_result)  # Output: [1, 2, 3]

n = 2
last_n_result = get_last_n(example_list, n)
print(last_n_result)  # Output: [4, 5]

[2, 3, 4]
[1, 2, 3]
[4, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [65]:
def remove_first_last(lst):
    """
    Removes the first and last elements from a list and returns the resulting sublist.
    :param lst: The input list.
    :return: A new list without the first and last elements.
    """
    return lst[1:-1] if len(lst) > 2 else []

def get_first_n(lst, n):
    """
    Extracts the first n elements from a list.
    :param lst: The input list.
    :param n: Number of elements to extract.
    :return: A new list containing the first n elements.
    """
    return lst[:n]

def get_last_n(lst, n):
    """
    Extracts the last n elements from a list.
    :param lst: The input list.
    :param n: Number of elements to extract.
    :return: A new list containing the last n elements.
    """
    return lst[-n:]

def reverse_skip(lst):
    """
    Extracts elements in reverse order, starting from the second-to-last element and skipping one element in between.
    :param lst: The input list.
    :return: A new list with every second element in reverse order.
    """
    return lst[-2::-2]

# Example usage
example_list = [1, 2, 3, 4, 5, 6]
result = remove_first_last(example_list)
print(result)  # Output: [2, 3, 4]

n = 3
first_n_result = get_first_n(example_list, n)
print(first_n_result)  # Output: [1, 2, 3]

n = 2
last_n_result = get_last_n(example_list, n)
print(last_n_result)  # Output: [5, 6]

reverse_skip_result = reverse_skip(example_list)
print(reverse_skip_result)  # Output: [5, 3, 1]


[2, 3, 4, 5]
[1, 2, 3]
[5, 6]
[5, 3, 1]


1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [68]:
def flatten(lst):
    flattened_list = []
    
    for item in lst:
        if isinstance(item, list):  # Check if the item is a list
            flattened_list.extend(flatten(item))  # Recursively flatten the nested list
        else:
            flattened_list.append(item)  # Add non-list items directly to the flattened list
            
    return flattened_list

# Example usage
nested_list = [[1, 2], [3, 4], [5]]
flattened = flatten(nested_list)
print(flattened)


[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [71]:
def access_nested_element(lst, indices):
    for index in indices:
        lst = lst[index]  # Access the next level of the list using the current index
    return lst  # The final element after all indices have been applied

# Example usage
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
element = access_nested_element(lst, indices)
print(element)


6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [74]:
def sum_nested(lst):
    total = 0
    
    for item in lst:
        if isinstance(item, list):  # If the item is a nested list
            total += sum_nested(item)  # Recursively call sum_nested to sum the elements in the nested list
        else:
            total += item  # Add the element if it's a number
    
    return total

# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print(result)


21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [80]:
def remove_element(lst, elem):
    for i in range(len(lst)):
        if isinstance(lst[i], list):  # If the item is a nested list
            lst[i] = remove_element(lst[i], elem)  # Recursively remove elem from the nested list
        else:
            # If the element is found, remove all occurrences of elem in the list
            while isinstance(lst[i], list) and elem in lst[i]:
                lst[i].remove(elem)
    
    return [sublist for sublist in lst if sublist != []]  # Remove empty sublists

# Example usage
lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
result = remove_element(lst, elem)
print(result)


[[1, 2], [3, 2], [4, 5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [83]:
def find_max(lst):
    max_element = float('-inf')  # Initialize with a very small value
    
    for item in lst:
        if isinstance(item, list):  # If the item is a nested list
            max_element = max(max_element, find_max(item))  # Recursively find the max in the nested list
        else:
            max_element = max(max_element, item)  # Compare and update the max value
    
    return max_element

# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)
print(result)


6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [86]:
def count_occurrences(lst, elem):
    count = 0
    
    for item in lst:
        if isinstance(item, list):  # If the item is a nested list
            count += count_occurrences(item, elem)  # Recursively count occurrences in the nested list
        else:
            count += item == elem  # Count the occurrences of elem in the current level
    
    return count

# Example usage
lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
result = count_occurrences(lst, elem)
print(result)


3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [91]:
def deep_flatten(lst):
    flattened_list = []
    
    for item in lst:
        if isinstance(item, list):  # If the item is a list, flatten it recursively
            flattened_list.extend(deep_flatten(item))  # Recursively flatten and add the result
        else:
            flattened_list.append(item)  # Add non-list elements directly to the flattened list
    
    return flattened_list

# Example usage
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)
print(result)


[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [94]:
def average_nested(lst):
    total = 0
    count = 0
    
    def flatten(lst):
        nonlocal total, count
        for item in lst:
            if isinstance(item, list):  # If the item is a nested list
                flatten(item)  # Recursively flatten the nested list
            else:
                total += item  # Add the number to the total
                count += 1  # Increase the count of numbers
    
    flatten(lst)
    return total / count if count != 0 else 0  # Return the average, avoid division by zero

# Example usage
nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)
print(result)


3.5


In [98]:
import numpy as np
# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
    print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
5
Dimension: 0
Data type: int32

Array:
[1 2 3]
Dimension: 1
Data type: int32

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int32



In [100]:
# For a 1-D array:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d.ndim) # Output: 1
# For a 2-D array:
arr_2d = np.array([[1, 2, 3],
[4, 5, 6]])
print(arr_2d.ndim) # Output: 2
#For a 3-D array:
arr_3d = np.array([[[1, 2, 3],
[4, 5, 6]],
[[7, 8, 9],
[10, 11, 12]]])
print(arr_3d.ndim) # Output: 3

1
2
3


In [102]:
print(arr_1d.shape) # Output: (5,)
print(arr_2d.shape) # Output: (2, 3)
print(arr_3d.shape) # Output: (2, 2, 3)

(5,)
(2, 3)
(2, 2, 3)


In [104]:
print(arr_1d.size) # Output: 5
print(arr_2d.size) # Output: 6
print(arr_3d.size) # Output: 12

5
6
12


In [106]:
print(arr_1d.dtype) # Output: int64 (or int32)
arr_float = np.array([1.1, 2.2, 3.3])
print(arr_float.dtype) # Output: float64

int32
float64


In [108]:
print(arr_1d.itemsize) # Output: 8 (for int64)

4


In [110]:
print(arr_1d.nbytes) # Output: 40 (5 elements \times 8 bytes each for int64)

20


In [112]:
print(arr_2d.T)
# Output:
# [[1 4]
# [2 5]
# [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [114]:
for item in arr_2d.flat:
    print(item, end=" ") # Output: 1 2 3 4 5 6

1 2 3 4 5 6 

In [116]:
arr_complex = np.array([1+2j, 3+4j])
print(arr_complex.real) # Output: [1. 3.]
print(arr_complex.imag) # Output: [2. 4.]

[1. 3.]
[2. 4.]


In [118]:
arr_float = arr_2d.astype(float)
print(arr_float)
# Output:
# [[1. 2. 3.]
# [4. 5. 6.]]

[[1. 2. 3.]
 [4. 5. 6.]]


In [120]:
lst = [[1, 2], [3, 4]]
print(lst.shape)
# Error: List has no .shape attribute
#Fixing the Error:
arr = np.array(lst)
print(arr.shape) # Output: (2, 2)

AttributeError: 'list' object has no attribute 'shape'

In [122]:
arr = np.array([1, 2, 3])
print(arr.shape[1]) # Error: 1D array only has one dimension
# Fixing the Error
if len(arr.shape) > 1:
    print(arr.shape[1]) # Access only if it’s valid

IndexError: tuple index out of range

In [124]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape()) # Error: .shape is an attribute, not a function
print(arr.shape) # Correct usage

TypeError: 'tuple' object is not callable

In [126]:
a = np.array([[1, 2], [3, 4]])
b = np.array([1, 2, 3])
print(a + b) # Error: Shapes (2,2) and (3,) are not compatible

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [128]:
large_array = np.ones((100000, 100000)) # May cause MemoryError

MemoryError: Unable to allocate 74.5 GiB for an array with shape (100000, 100000) and data type float64

In [130]:
import numpy as np
# Create an array with shape (2, 3)
array = np.array([[1, 2, 3],
[4, 5, 6]])

# Reshape to (3, 2), keeping 6 elements
reshaped_array = array.reshape(3, 2)
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)
# Expected Outputs:
# Original Shape: (2, 3)
# Reshaped Shape: (3, 2)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


In [132]:
array = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_array = array.reshape(4, 2)
# Error: cannot reshape array of size 6 into shape (4, 2)

ValueError: cannot reshape array of size 6 into shape (4,2)

In [134]:
import numpy as np
a = np.arange(1, 10)
print(a)
x = range(1, 10)
print(x) # x is an iterator
print(list(x))
# further arange examples:
x = np.arange(10.4)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [136]:
import numpy as np
# 50 values between 1 and 10:
print(np.linspace(1, 10))
# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))
# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [138]:
import numpy as np
# Create arrays of specified shapes
ones_array = np.ones((2, 3)) # Shape: (2, 3)
zeros_array = np.zeros((3, 2)) # Shape: (3, 2)
empty_array = np.empty((2, 2)) # Shape: (2, 2)
identity_matrix = np.eye(3) # Shape: (3, 3)
print(ones_array, zeros_array, empty_array, identity_matrix, sep=’\n\n’)

SyntaxError: invalid character '’' (U+2019) (596432151.py, line 7)

In [146]:
import numpy as np
array_from_list = np.array([1, 2, 3]) # [1 2 3]
array_from_tuple = np.array((4, 5, 6)) # [4 5 6]
array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]]) # [[1 2 3] [4 5 6]]
print(array_from_list, array_from_tuple, array_from_nested_list, sep='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [144]:
import numpy as np
# Existing Array of Shape:(2,3)
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Creating Array with Shape of existing array:
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape) #
Shape: (2,3)
print(arr, zeros, ones, empty, sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [150]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]]) # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]]) # Shape: (2, 2)
# Stacking examples
hstacked = np.hstack((arr1, arr2))
# Output hstack: [[1 2 5 6] [3 4 7 8]]
vstacked = np.vstack((arr1, arr2))
# Output vstack[[1 2] [3 4] [5 6] [7 8]]
colstacked = np.column_stack((arr1[0], arr2[0]))
# Output column stack: [[1 5] [2 6]]
print(hstacked, vstacked, colstacked, sep='\n')

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 5]
 [2 6]]


In [154]:
import numpy as np
# Creating two 3D arrays
arr1 = np.array([[[1], [2]], [[3], [4]]]) # Shape: (2, 2, 1)
arr2 = np.array([[[5], [6]], [[7], [8]]]) # Shape: (2, 2, 1)
# Concatenate along axis 0 (vertical stacking)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
# Shape of concat_axis0: (4, 2, 1), arr1 is stacked on top of arr2
# Concatenate along axis 1 (horizontal stacking)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
# Shape of concat_axis1: (2, 4, 1), arr1 and arr2 are placed side by side
# Concatenate along axis 2 (depth stacking)
concat_axis2 = np.concatenate((arr1, arr2), axis=2)
# Shape of concat_axis2: (2, 2, 2), arr1 and arr2 are stacked in depth (thirddimension)
# Displaying the results
print("Concatenation along axis 0 (Vertical stacking):\n", concat_axis0)
print("Shape of concatenated array along axis 0:", concat_axis0.shape)
print("\nConcatenation along axis 1 (Horizontal stacking):\n", concat_axis1)
print("Shape of concatenated array along axis 1:", concat_axis1.shape)
print("\nConcatenation along axis 2 (Depth stacking):\n", concat_axis2)
print("Shape of concatenated array along axis 2:", concat_axis2.shape)

Concatenation along axis 0 (Vertical stacking):
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]
Shape of concatenated array along axis 0: (4, 2, 1)

Concatenation along axis 1 (Horizontal stacking):
 [[[1]
  [2]
  [5]
  [6]]

 [[3]
  [4]
  [7]
  [8]]]
Shape of concatenated array along axis 1: (2, 4, 1)

Concatenation along axis 2 (Depth stacking):
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Shape of concatenated array along axis 2: (2, 2, 2)


In [158]:
import numpy as np
# Incorrect shapes
arr1 = np.array([[1, 2], [3, 4]]) # shape (2, 2)
arr2 = np.array([5, 6]) # shape (2,)
# Attempting horizontal stack
try:
    hstacked = np.hstack((arr1, arr2)) # Error due to dimension mismatch
except ValueError as e:
    print(f"Error: {e}")
# Solution: Reshape arr2 to match arr1’s dimensions
arr2 = np.array([5, 6]).reshape(2, 1) # shape (2, 1)
hstacked = np.hstack((arr1, arr2)) # No error
print(hstacked)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
[[1 2 5]
 [3 4 6]]


In [160]:
arr1 = np.array([[1, 2], [3, 4]], dtype=int)
arr2 = np.array([5, 6], dtype=float)
# Attempting horizontal stack (this will work, but can lead to unexpected results)
hstacked = np.hstack((arr1, arr2))
print(hstacked)
# Solution: Convert the data types to match each other explicitly, if needed:
arr2 = np.array([5, 6], dtype=int) # Match the type of arr1
hstacked = np.hstack((arr1, arr2)) # Works fine
print(hstacked)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [164]:
arr1 = np.array([[[1, 2], [3, 4]]]) # shape (1, 2, 2)
arr2 = np.array([[5, 6], [7, 8]]) # shape (2, 2)
# Attempting stacking with 3D and 2D arrays
try:
    vstacked = np.vstack((arr1, arr2)) # Error due to too many dimensions
except ValueError as e:
    print(f"Error: {e}")
# Solution: Reshape arr1 to be 2D (or flatten it) before stacking
arr1 = arr1.reshape(2, 2) # Now it’s shape (2, 2)
vstacked = np.vstack((arr1, arr2)) # Works fine
print(vstacked)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [166]:
import numpy as np
# Creating a 2D array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Accessing elements using indexing
print(array[0, 1]) # Output: 2 (first row, second column)
print(array[-1, -1]) # Output: 9 (last row, last column)
# Slicing the array
print(array[0:2, 1:3]) # Output: [[2, 3], [5, 6]]

2
9
[[2 3]
 [5 6]]


In [168]:
import numpy as np
# Creating a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
# Attempting to access an element out of bounds
try:
    print(array[2, 1])
except IndexError as e:
    print(f"Error: {e}")

Error: index 2 is out of bounds for axis 0 with size 2


In [170]:
import numpy as np
# Example of basic ufuncs: square and square root
arr = np.array([1, 4, 9, 16])
# Square every element
squared = np.square(arr)
# Square root of every element
sqrt = np.sqrt(arr)
print(f"Squared: {squared}")
print(f"Square root: {sqrt}")

Squared: [  1  16  81 256]
Square root: [1. 2. 3. 4.]


In [172]:
import numpy as np
# Trigonometric ufuncs
angles = np.array([0, np.pi / 4, np.pi / 2])
sine_values = np.sin(angles)
# Logarithmic ufuncs
log_values = np.log(arr)

In [174]:
import numpy as np
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
product = np.dot(A, B)
# Compute determinant
det = np.linalg.det(A)
# Compute inverse
inverse = np.linalg.inv(A)
# Compute eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(A)
print(f"Matrix Product:\n{product}")
print(f"Determinant: {det}")
print(f"Inverse:\n{inverse}")
print(f"Eigenvalues: {eigvals}, Eigenvectors:\n{eigvecs}")

Matrix Product:
[[19 22]
 [43 50]]
Determinant: -2.0000000000000004
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132], Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [176]:
import numpy as np
A = np.array([[1], [2], [3]]) # Shape (3,1) 3 rows, 1 column
B = np.array([10, 20, 30]) # Shape (3,) 1D array (3 elements)
C = A + B # Works! Result shape: (3,3)
print(C)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [178]:
A = np.array([[1, 2, 3]]) # Shape (1,3)
B = np.array([[4], [5], [6]]) # Shape (3,1)
C = A + B #Works! Result shape: (3,3)
print(C)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [180]:
A = np.ones((3,2)) # Shape (3,2)
B = np.ones((2,3)) # Shape (2,3)
C = A + B #ValueError: operands could not be broadcast together

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [182]:
import numpy as np
import time
# Create two large arrays
size = 10**6
a = np.random.rand(size)
b = np.random.rand(size)
# Using a loop
start_time = time.time()
result_loop = np.zeros(size)
for i in range(size):
    result_loop[i] = a[i] + b[i]
end_time = time.time()
loop_time = end_time - start_time
print(f"Loop Execution Time: {loop_time:.5f} seconds")
# Using NumPy’s vectorized operations
start_time = time.time()
result_vectorized = a + b # Element-wise addition
end_time = time.time()
vectorized_time = end_time - start_time
print(f"Vectorized Execution Time: {vectorized_time:.5f} seconds")
# Performance improvement factor
speedup = loop_time / vectorized_time
print(f"Vectorization is approximately {speedup:.2f} times faster!")

Loop Execution Time: 0.44811 seconds
Vectorized Execution Time: 0.00206 seconds
Vectorization is approximately 217.66 times faster!


Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [185]:
import numpy as np

# Task 1: Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)

# Task 2: Initialize an all-ones array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll Ones Array (4x2):\n", ones_array)

# Task 3: Return a new array of given shape and type, filled with a fill value
shape = (3, 3)
fill_value = 7
filled_array = np.full(shape, fill_value)
print("\nArray filled with", fill_value, ":\n", filled_array)

# Task 4: Return a new array of zeros with same shape and type as a given array
existing_array = np.array([[1, 2], [3, 4]])
zeros_array = np.zeros_like(existing_array)
print("\nArray of Zeros with the same shape and type as existing_array:\n", zeros_array)

# Task 5: Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(existing_array)
print("\nArray of Ones with the same shape and type as existing_array:\n", ones_like_array)

# Task 6: Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array from new_list:\n", numpy_array)


Empty Array (2x2):
 [[0.82456484 0.41597356]
 [0.56576746 0.90937671]]

All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 7 :
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Array of Zeros with the same shape and type as existing_array:
 [[0 0]
 [0 0]]

Array of Ones with the same shape and type as existing_array:
 [[1 1]
 [1 1]]

Converted NumPy Array from new_list:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [188]:
import numpy as np

# Task 1: Create an array with values ranging from 10 to 49.
arr_10_49 = np.arange(10, 50)
print("Array with values from 10 to 49:\n", arr_10_49)

# Task 2: Create a 3x3 matrix with values ranging from 0 to 8.
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:\n", matrix_3x3)

# Task 3: Create a 3x3 identity matrix.
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# Task 4: Create a random array of size 30 and find the mean of the array.
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array of size 30:\n", random_array)
print("\nMean of the random array:", mean_value)

# Task 5: Create a 10x10 array with random values and find the minimum and maximum values.
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Random Array:\n", random_10x10)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)

# Task 6: Create a zero array of size 10 and replace the 5th element with 1.
zero_array = np.zeros(10)
zero_array[4] = 1  # 5th element is at index 4 (0-based indexing)
print("\nZero array with 5th element replaced with 1:\n", zero_array)

# Task 7: Reverse an array arr = [1, 2, 0, 0, 4, 0].
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:\n", reversed_arr)

# Task 8: Create a 2d array with 1 on the border and 0 inside.
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on the border and 0 inside:\n", border_array)

# Task 9: Create an 8x8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Fill alternate positions
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)


Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30:
 [0.34378615 0.07679347 0.90743211 0.24289422 0.04186584 0.79814758
 0.44306804 0.32556582 0.09417028 0.95164588 0.77914234 0.93652967
 0.36167905 0.24580384 0.19954001 0.40303494 0.79837186 0.01165784
 0.11258598 0.00368211 0.56097255 0.0368592  0.15551208 0.33485095
 0.20288516 0.14465847 0.33821035 0.89403749 0.79725165 0.50560918]

Mean of the random array: 0.40160813686455127

10x10 Random Array:
 [[0.41724126 0.220462   0.70112967 0.8198909  0.67413637 0.15373
  0.51113772 0.16518566 0.97159799 0.11969508]
 [0.30229181 0.07430711 0.70084555 0.92528396 0.63631865 0.77050254
  0.49139885 0.61215304 0.01623476 0.42994764]
 [0.26486202 0.41150366 0.06991302 0.59171046 0.05020105 0

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [194]:
import numpy as np

# Define arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task 1: Add the two arrays
add_result = x + y
print("Addition of x and y:\n", add_result)

# Task 2: Subtract the two arrays
subtract_result = x - y
print("\nSubtraction of x and y:\n", subtract_result)

# Task 3: Multiply the array with any integer of your choice
mult_result = x * 2  # Multiply x by 2
print("\nMultiplying x by 2:\n", mult_result)

# Task 4: Find the square of each element of the array
square_result = np.square(x)
print("\nSquare of each element in x:\n", square_result)

# Task 5: Find the dot product between:
# - v and w
dot_v_w = np.dot(v, w)
print("\nDot product between v and w:", dot_v_w)

# - x and v
dot_x_v = np.dot(x, v)
print("\nDot product between x and v:\n", dot_x_v)

# - x and y
dot_x_y = np.dot(x, y)
print("\nDot product between x and y:\n", dot_x_y)

# Task 6: Concatenate x and y along the row and concatenate v and w along the column
concatenate_x_y = np.concatenate((x, y), axis=0)  # Concatenate x and y along row
print("\nConcatenation of x and y along row:\n", concatenate_x_y)

concatenate_v_w = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)  # Concatenate v and w along column
print("\nConcatenation of v and w along column:\n", concatenate_v_w)

# Task 7: Concatenate x and v; if you get an error, observe and explain why you got the error.
try:
    concatenate_x_v = np.concatenate((x, v), axis=0)  # Trying to concatenate x and v along row
    print("\nConcatenation of x and v along row:\n", concatenate_x_v)
except ValueError as e:
    print("\nError when concatenating x and v:", e)


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplying x by 2:
 [[ 2  4]
 [ 6 10]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product between v and w: 219

Dot product between x and v:
 [29 77]

Dot product between x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along column:
 [[ 9 11]
 [10 12]]

Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [197]:
import numpy as np

# Define matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Task 1: Prove A.A^-1 = I (Identity Matrix)
# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Multiply A with its inverse
result = np.dot(A, A_inv)
print("A * A^-1:\n", result)
print("Identity Matrix:\n", np.eye(2))  # Identity Matrix

# Task 2: Prove AB ≠ BA
# Multiply A and B
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("BA:\n", BA)
print("\nAre AB and BA equal? ", np.array_equal(AB, BA))

# Task 3: Prove (AB)^T = B^T * A^T
# Transpose of AB
AB_T = np.transpose(AB)

# Transpose of B and A
B_T = np.transpose(B)
A_T = np.transpose(A)

# Check if (AB)^T = B^T * A^T
print("\n(AB)^T:\n", AB_T)
print("B^T * A^T:\n", np.dot(B_T, A_T))
print("\nIs (AB)^T equal to B^T * A^T? ", np.array_equal(AB_T, np.dot(B_T, A_T)))

# Task 4: Solve the system of linear equations using the inverse method
# The system is represented as: AX = B, where
# A = [[2, -3, 1],
#      [1, -1, 2],
#      [3, 1, -1]]
# B = [-1, -3, 9]

A_linear = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_linear = np.array([-1, -3, 9])

# Solve for X using the inverse method: X = A^-1 * B
A_inv_linear = np.linalg.inv(A_linear)
X = np.dot(A_inv_linear, B_linear)
print("\nSolution of linear equations using inverse method:\n", X)

# Task 5: Solve the system of linear equations using np.linalg.solve function
X_solve = np.linalg.solve(A_linear, B_linear)
print("\nSolution using np.linalg.solve function:\n", X_solve)


A * A^-1:
 [[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]
Identity Matrix:
 [[1. 0.]
 [0. 1.]]

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]

Are AB and BA equal?  False

(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]

Is (AB)^T equal to B^T * A^T?  True

Solution of linear equations using inverse method:
 [ 2.  1. -2.]

Solution using np.linalg.solve function:
 [ 2.  1. -2.]


In [ ]:
import numpy as np
import time

# 1. Element-wise Addition
# Using Python Lists
list_size = 1000000
list1 = [i for i in range(list_size)]
list2 = [i for i in range(list_size)]

# Measure time for Python lists
start_time = time.time()
list_add = [list1[i] + list2[i] for i in range(list_size)]
python_list_add_time = time.time() - start_time
print(f"Element-wise Addition (Python List) took: {python_list_add_time:.5f} seconds")

# Using NumPy Arrays
np_list1 = np.arange(list_size)
np_list2 = np.arange(list_size)

# Measure time for NumPy arrays
start_time = time.time()
np_add = np_list1 + np_list2
numpy_add_time = time.time() - start_time
print(f"Element-wise Addition (NumPy Array) took: {numpy_add_time:.5f} seconds")


# 2. Element-wise Multiplication
# Using Python Lists
start_time = time.time()
list_multiply = [list1[i] * list2[i] for i in range(list_size)]
python_list_multiply_time = time.time() - start_time
print(f"Element-wise Multiplication (Python List) took: {python_list_multiply_time:.5f} seconds")

# Using NumPy Arrays
start_time = time.time()
np_multiply = np_list1 * np_list2
numpy_multiply_time = time.time() - start_time
print(f"Element-wise Multiplication (NumPy Array) took: {numpy_multiply_time:.5f} seconds")


# 3. Dot Product
# Using Python Lists
start_time = time.time()
dot_product = sum(list1[i] * list2[i] for i in range(list_size))
python_list_dot_product_time = time.time() - start_time
print(f"Dot Product (Python List) took: {python_list_dot_product_time:.5f} seconds")

# Using NumPy Arrays
start_time = time.time()
np_dot_product = np.dot(np_list1, np_list2)
numpy_dot_product_time = time.time() - start_time
print(f"Dot Product (NumPy Array) took: {numpy_dot_product_time:.5f} seconds")


# 4. Matrix Multiplication
# Create two random 1000x1000 matrices
matrix_size = 1000
matrix1 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]
matrix2 = [[i - j for j in range(matrix_size)] for i in range(matrix_size)]

# Using Python Lists - Matrix Multiplication
start_time = time.time()
python_matrix_multiply = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(matrix_size)) for j in range(matrix_size)] for i in range(matrix_size)]
python_list_matrix_multiply_time = time.time() - start_time
print(f"Matrix Multiplication (Python List) took: {python_list_matrix_multiply_time:.5f} seconds")

# Using NumPy Arrays - Matrix Multiplication
np_matrix1 = np.random.rand(matrix_size, matrix_size)
np_matrix2 = np.random.rand(matrix_size, matrix_size)

start_time = time.time()
np_matrix_multiply = np.dot(np_matrix1, np_matrix2)
numpy_matrix_multiply_time = time.time() - start_time
print(f"Matrix Multiplication (NumPy Array) took: {numpy_matrix_multiply_time:.5f} seconds")


Element-wise Addition (Python List) took: 0.35173 seconds
Element-wise Addition (NumPy Array) took: 0.00300 seconds
Element-wise Multiplication (Python List) took: 0.21000 seconds
Element-wise Multiplication (NumPy Array) took: 0.00300 seconds
Dot Product (Python List) took: 0.28699 seconds
Dot Product (NumPy Array) took: 0.00100 seconds
